### ISSUE TITLE
An error happened when i run your code.

### ISSUE THREAD

**Issue by leerduo** [djvine/pySART#1]
when i run the following code:

``` Python
pysart = pysart(*generate_phantom())
pysart.sart()
```

I got an error：

```
C:\Python27\python.exe D:/Users/Administrator/PycharmProjects/ART/arttest/maintest.py
'latex' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/Users/Administrator/PycharmProjects/ART/arttest/maintest.py", line 16, in <module>
    pysart.sart()
  File "D:\Users\Administrator\PycharmProjects\ART\arttest\pySART.py", line 69, in sart
    self.update_figure(pslice=True)
  File "D:\Users\Administrator\PycharmProjects\ART\arttest\pySART.py", line 147, in update_figure
    pylab.draw()
  File "C:\Python27\lib\site-packages\matplotlib\pyplot.py", line 571, in draw
    get_current_fig_manager().canvas.draw()
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 349, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\figure.py", line 1085, in draw
    func(*args)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2110, in draw
    a.draw(renderer)
  File "C:\Python27\lib\site-packages\matplotlib\artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axis.py", line 1116, in draw
    renderer)
  File "C:\Python27\lib\site-packages\matplotlib\axis.py", line 1065, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "C:\Python27\lib\site-packages\matplotlib\text.py", line 798, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\Python27\lib\site-packages\matplotlib\text.py", line 311, in _get_layout
    ismath=False)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_agg.py", line 223, in get_text_width_height_descent
    renderer=self)
  File "C:\Python27\lib\site-packages\matplotlib\texmanager.py", line 670, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "C:\Python27\lib\site-packages\matplotlib\texmanager.py", line 417, in make_dvi
    report))
RuntimeError: LaTeX was not able to process the following string:
'lp'
Here is the full report generated by LaTeX: 



Process finished with exit code 1
```

How to solve the problem?

**Comment by djvine** [comment]
Hi Chen,

this code probably doesn't work on windows, sorry.

In any case, this project has been superseded by a much better package for tomographic reconstruction: https://github.com/tomopy/tomopy. I suggest you switch to tomopy.

Best,
David

**Comment by leerduo** [comment]
Thanks. @djvine
